---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "http://app-web-1:4000"
    includePaths: []
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    context: "Default Context"
    user: ""
    url: "http://app-web-1:4000"
    maxDuration: 0
    maxDepth: 0
    maxChildren: 0
    acceptCookies: true
    handleODataParametersVisited: true
    handleParameters: "USE_ALL"
    maxParseSizeBytes: 100000
    parseComments: false
    parseGit: false
    parseRobotsTxt: false
    parseSitemapXml: false
    parseSVNEntries: false
    postForm: true
    processForm: true
    requestWaitTime: 0
    sendRefererHeader: true
    userAgent: ""
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 1000
    name: "At least 100 URLs found"
    type: "stats"
  name: "spider"
  type: "spider"
- parameters:
    context: "Default Context"
    user: ""
    url: "http://app-web-1:4000"
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 32
    maxCrawlStates: 0
    eventWait: 1
    reloadWait: 1
    clickDefaultElems: true
    clickElemsOnce: true
    randomInputs: true
    inScopeOnly: true
    runOnlyIfModern: false
  name: "spiderAjax"
  type: "spiderAjax"
- parameters:
    template: "traditional-html"
    reportDir: "/zap"
    reportFile: "ZAP_REPORT"
    reportTitle: "ZAP Baseline Scan Report"
    reportDescription: ""
    displayReport: false
  risks:
    - "info"
    - "low"
    - "medium"
    - "high"
  confidences:
    - "falsepositive"
    - "low"
    - "medium"
    - "high"
    - "confirmed"
  sections:
    - "instancecount"
    - "alertdetails"
    - "alertcount"
  name: "report"
  type: "report"
- parameters:
    template: "traditional-md"
    reportDir: "/zap"
    reportFile: "ZAP_ALERT_REPORT"
    reportTitle: "ZAP Scanning Report"
    reportDescription: "This is report that should contain only alerts that should\
      \ fail the pipeline and be revisited by a team member"
    displayReport: false
  risks:
    - "low"
    - "medium"
    - "high"
  confidences:
    - "low"
    - "medium"
    - "high"
    - "confirmed"
  sections:
    - "alertdetails"
    - "alertcount"
  name: "alert-report"
  type: "report"
