name: OWASP ZAP SCAN
on: workflow_dispatch

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
          ref: master
          
       - name: Create Docker Network
         run: |
          docker network create mynetwork
          docker-compose build
          docker-compose up --detach 
          docker ps 
          docker network connect mynetwork docker-compose_application_web_1
          docker network connect mynetwork docker-compose_application_mongo_1
          docker network inspect mynetwork
          
       - name: Set up testing environment
         run: |
            docker run -d -i -t --network=mynetwork --name OWASPZAP -v $(pwd):/zap/wrk/:rw owasp/zap2docker-stable
            docker ps
       
       - name: Copy test files to the OWASP ZAP image
         run: docker cp OWASPZAP_scanns/NodeGoat_baseline.yaml OWASPZAP:/zap/NodeGoat_baseline.yaml 

       - name: Execute the scan
         run: |
           docker exec -i OWASPZAP zap.sh -cmd -autorun /zap/NodeGoat_baseline.yaml
           docker exec OWASPZAP sh -c ls
           docker exec -i OWASPZAP pwd
           docker cp OWASPZAP:/zap/ZAP_REPORT.html .
           docker cp OWASPZAP:/zap/ZAP_ALERT_REPORT.md .


       - name: Upload HTML Report
         uses: actions/upload-artifact@v3
         with:
           name: ZAP_REPORT.html
           path: ZAP_REPORT.html

       - name: Upload MD Report
         uses: actions/upload-artifact@v3
         with:
           name: ZAP_ALERT_REPORT.md
           path: ZAP_ALERT_REPORT.md
